import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
df=pd.read_csv("Datasets\\auto-mpg.csv")
# print(df)
# print(df.info())
# print(df['car name'])
# print(type(df['car name']))
# print("ILOC")
# print(df.iloc[1])
# print("LOC")
# print(df.loc[1])
# print(df.iloc[1:5,3])
# print(df.loc[1:5])
# print(df.corr(numeric_only=True))
# pd.plotting.scatter_matrix(df,figsize=[15,15],marker='v',alpha=0.7)
# plt.show()
da=df['horsepower'].replace('?',0.0)
print(da)
df.info()