import pandas as pd
csv=pd.read_csv("ipl-matches.csv")
print("First Task : Display First 5 Rows and Last 5 Rows :")
print(csv.head())
print("Second Task : Display Information of Dataset : ")
print(csv.info())
print("Third Task : Shape Of Dataset : ")
print(csv.shape)
print("Fourth Task : Missing Values")
print(csv.isna().sum)
print("Fifth Task : Display Statical Analysis : ")
print(csv.describe())
print("Sixth Task : Display Object Types Of Datasets")
print(csv.describe(include='object'))
print("Seventh task : How Many gone in super over ?")
print(csv[csv['SuperOver']=="Y"].shape[0])
print("Eigth task : How Many won by csk at kolkata ?")
print(csv[(csv['City']=='Kolkata') & (csv["WinningTeam"]=="Chennai Super Kings")].shape[0])
print("Ninth Task: How Many Macthes GT Won the toss and select bat and won th match ")
